version: '3'

services:
  webapp:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: >
      sh -c "python app.py"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/noter
      - SECRET_KEY=my_precious
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=noter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - webapp